/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fp;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Manuel Gomez
 */
public class FP extends javax.swing.JFrame {

    /**
     * Creates new form FP
     */
    public FP() {
        initComponents();
        setLocationRelativeTo(null);
        addPopup();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTsecondTangent = new javax.swing.JTextField();
        jTfirstTangent = new javax.swing.JTextField();
        jTbendLine = new javax.swing.JTextField();
        jTbendRadius = new javax.swing.JTextField();
        jTtotalDepth = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioMM = new javax.swing.JRadioButton();
        jRadioIN = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flange Plate Calculator for FORAN v0.2");
        setResizable(false);

        jLabel2.setText("Bend line (A+ (B/2))");

        jLabel3.setText("Second tangent (A+B)");

        jLabel4.setText("Total depth (A+B+C)");

        jLabel8.setText("Inner Radius (R)");

        jLabel9.setText("Web:");

        jLabel10.setText("Flange:");

        jLabel11.setText("Thickness:");

        jTextField1.setText("0.00");

        jTextField2.setText("0.00");

        jTextField3.setText("0.00");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fp/FLANGEPLATE.png"))); // NOI18N

        jLabel16.setText("First tangent (A)");

        jLabel15.setText("in");

        jLabel18.setText("in");

        jLabel19.setText("in");

        jTsecondTangent.setEditable(false);
        jTsecondTangent.setText("0.00");

        jTfirstTangent.setEditable(false);
        jTfirstTangent.setText("0.00");

        jTbendLine.setEditable(false);
        jTbendLine.setText("0.00");

        jTbendRadius.setEditable(false);
        jTbendRadius.setText("0.00");

        jTtotalDepth.setEditable(false);
        jTtotalDepth.setText("0.00");

        jLabel25.setText("in");

        jLabel26.setText("in");

        jLabel27.setText("in");

        jLabel28.setText("in");

        jLabel29.setText("in");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("All input units in decimal or fractional inches,");

        jLabel17.setText("All output units in decimal inches.");

        jLabel22.setText("to use fractional notation use \" and ' symbols.");

        buttonGroup1.add(jRadioMM);
        jRadioMM.setText("Metric");
        jRadioMM.setActionCommand("jRadioMM");
        jRadioMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMMActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioIN);
        jRadioIN.setSelected(true);
        jRadioIN.setText("Inches");
        jRadioIN.setActionCommand("jRadioIN");
        jRadioIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioMM)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTtotalDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTbendRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTbendLine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTfirstTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTsecondTangent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel22)
                            .addComponent(jLabel14))
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jRadioIN)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioMM)
                            .addComponent(jRadioIN))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfirstTangent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTbendLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTsecondTangent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTtotalDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTbendRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel29))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Flange Plates", jPanel1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fp/construction.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Flange Brackets", jPanel2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fp/construction.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unit Converter", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Flange Plates");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calculateFP();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMMActionPerformed
        jLabel15.setText("mm");
        jLabel18.setText("mm");
        jLabel19.setText("mm");
        jLabel25.setText("mm");
        jLabel26.setText("mm");
        jLabel27.setText("mm");
        jLabel28.setText("mm");
        jLabel29.setText("mm");
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jTsecondTangent.setText("0");
        jTfirstTangent.setText("0");
        jTbendLine.setText("0");
        jTbendRadius.setText("0");
        jTtotalDepth.setText("0");
        jLabel14.setText(" ");
        jLabel22.setText(" ");
        jLabel17.setText(" ");
        
    }//GEN-LAST:event_jRadioMMActionPerformed

    private void jRadioINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioINActionPerformed
        jLabel15.setText("in");
        jLabel18.setText("in");
        jLabel19.setText("in");
        jLabel25.setText("in");
        jLabel26.setText("in");
        jLabel27.setText("in");
        jLabel28.setText("in");
        jLabel29.setText("in");
        jTextField1.setText("0.00");
        jTextField2.setText("0.00");
        jTextField3.setText("0.00");
        jTextField1.setText("0.00");
        jTextField2.setText("0.00");
        jTextField3.setText("0.00");
        jTsecondTangent.setText("0.00");
        jTfirstTangent.setText("0.00");
        jTbendLine.setText("0.00");
        jTbendRadius.setText("0.00");
        jTtotalDepth.setText("0.00");
        jLabel14.setText("All input units in decimal or fractional inches,");
        jLabel22.setText("to use fractional notation use \" and ' symbols.");
        jLabel17.setText("All output units in decimal inches.");
    }//GEN-LAST:event_jRadioINActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioIN;
    private javax.swing.JRadioButton jRadioMM;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTbendLine;
    private javax.swing.JTextField jTbendRadius;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTfirstTangent;
    private javax.swing.JTextField jTsecondTangent;
    private javax.swing.JTextField jTtotalDepth;
    // End of variables declaration//GEN-END:variables

    public void calculateFP() {
        float web, flange, thickness, internalRadius, midRadius, externalRadius, arcLength, firstTangent, bendLine, secondTangent, flatFlange, totalDepth;

        if (jRadioIN.isSelected()) {
            try {
                web = ImperialUtils.fractionalInchesToDecimalInches(jTextField1.getText());
                flange = ImperialUtils.fractionalInchesToDecimalInches(jTextField2.getText());
                thickness = ImperialUtils.fractionalInchesToDecimalInches(jTextField3.getText());

                internalRadius = ImperialUtils.radiusCalculatorIN(thickness);
                midRadius = internalRadius + (thickness / 2f);
                externalRadius = internalRadius + (thickness);

                firstTangent = web - externalRadius;
                arcLength = 2 * (float) Math.PI * midRadius / 4f;
                bendLine = firstTangent + (arcLength / 2f);
                secondTangent = firstTangent + arcLength;
                flatFlange = flange - externalRadius;
                totalDepth = firstTangent + arcLength + flatFlange;

                jTfirstTangent.setText(String.format("%.2f", firstTangent));
                jTbendLine.setText(String.format("%.2f", bendLine));
                jTsecondTangent.setText(String.format("%.2f", secondTangent));
                jTtotalDepth.setText(String.format("%.2f", totalDepth));
                jTbendRadius.setText(String.format("%.2f", internalRadius));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Invalid input");
            }
        }else{
        try {
                web = Float.parseFloat(jTextField1.getText());
                flange = Float.parseFloat(jTextField2.getText());
                thickness = Float.parseFloat(jTextField3.getText());

                internalRadius = ImperialUtils.radiusCalculatorMM(thickness);
                midRadius = internalRadius + (thickness / 2f);
                externalRadius = internalRadius + (thickness);

                firstTangent = web - externalRadius;
                arcLength = 2 * (float) Math.PI * midRadius / 4f;
                bendLine = firstTangent + (arcLength / 2f);
                secondTangent = firstTangent + arcLength;
                flatFlange = flange - externalRadius;
                totalDepth = firstTangent + arcLength + flatFlange;

                jTfirstTangent.setText(String.format("%.0f", firstTangent));
                jTbendLine.setText(String.format("%.0f", bendLine));
                jTsecondTangent.setText(String.format("%.0f", secondTangent));
                jTtotalDepth.setText(String.format("%.0f", totalDepth));
                jTbendRadius.setText(String.format("%.0f", internalRadius));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Invalid input");
            }
        
        }
        /*
            System.out.println("web:"+web);
            System.out.println("flange:"+flange);
            System.out.println("thickness:"+thickness);
            System.out.println("internalRadius:"+internalRadius);
            System.out.println("midRadius:"+midRadius);
            System.out.println("externalRadius:"+externalRadius);
            System.out.println("firstTangent:"+firstTangent);
            System.out.println("arcLength:"+arcLength);
            System.out.println("bendLine:"+bendLine);
            System.out.println("secondTangent:"+secondTangent);
            System.out.println("flatFlange:"+flatFlange);
            System.out.println("totalDepth:"+totalDepth);
        */
    }
    
    public void convertAll(){
        
    
    
    
    
    }

    public void addPopup() {
        JPopupMenu popup = new JPopupMenu();
        JMenuItem item = new JMenuItem(new DefaultEditorKit.CutAction());
        item.setText("Cut");
        popup.add(item);
        item = new JMenuItem(new DefaultEditorKit.CopyAction());
        item.setText("Copy");
        popup.add(item);
        item = new JMenuItem(new DefaultEditorKit.PasteAction());
        item.setText("Paste");
        popup.add(item);
        jTfirstTangent.setComponentPopupMenu(popup);
        jTbendLine.setComponentPopupMenu(popup);
        jTsecondTangent.setComponentPopupMenu(popup);
        jTtotalDepth.setComponentPopupMenu(popup);
        jTbendRadius.setComponentPopupMenu(popup);
        jTextField1.setComponentPopupMenu(popup);
        jTextField2.setComponentPopupMenu(popup);
        jTextField3.setComponentPopupMenu(popup);
    }



}
